#!/usr/bin/env ruby

require 'optparse'

class ServerDeploy

  def initialize(args)
    @app_dir     = File.expand_path('../../', __FILE__)
    @environment = 'production'
    @migrate     = false

    option_parser = OptionParser.new do |opts|
      opts.banner = "Usage: #{File.basename($0)} [options]"
      opts.on('-m', '--migrate', 'Perform database migrations.') do
        @migrate = true
      end
      opts.on('-h', '--help', 'Show this message.') do
        puts opts
        exit 1
      end
    end

    option_parser.parse!(args)

    if ENV['USER'] != 'passmaster'
      puts 'This script should be run as the passmaster user.'
      exit 1
    end
  end

  def deploy
    ENV['RAILS_ENV'] = @environment
    Dir.chdir(@app_dir) do
      system "git checkout master"
      system "git pull"
      system "git checkout #{@environment}"
      system "git reset --hard origin/#{@environment}"
      system "bundle install --quiet"
      system "bundle exec rake db:migrate" if @migrate
      system "bundle exec pumactl restart" if system "bundle exec pumactl status"
    end
  end

end

ServerDeploy.new(ARGV).deploy
