#!/usr/bin/env ruby

hostname = `hostname`

if hostname =~ /^ip-|^domU-/
  print `curl -s http://169.254.169.254/latest/meta-data/security-groups`.split("\n").reject { |sg| sg == 'passmaster' }.first
else
  print 'dev'
end
