#!/usr/bin/env ruby

# This script is called by upstart during server startup as root

class ServerStart

  def initialize
    @app_dir = File.expand_path('../../', __FILE__)
  end

  def exec
    `su - passmaster -c '#{@app_dir}/script/wrapper #{@app_dir}/script/server_deploy'`
  end

end

ServerStart.new.exec
