#!/usr/bin/env ruby

class UnicornTasks

  def initialize(args)
    @app_dir     = File.expand_path('../../', __FILE__)
    @command     = args.shift
    @environment = args.shift || 'development'
  end

  def exec
    Dir.chdir(@app_dir) do
      case @command
      when 'start'
        start_or_restart
      when 'restart'
        restart
      when 'stop'
        stop
      when 'status'
        status
      else
        print_usage
      end
    end
  end

  private

  def start_or_restart
    if unicorn_pid == ''
      system "bundle exec unicorn_rails -c config/unicorn.rb -E #{@environment} -D"
      puts "Started unicorn in #{@environment} mode."
    else
      restart
    end
  end

  def restart
    unless unicorn_pid == ''
      system "kill -USR2 #{unicorn_pid}"
      puts "Restarted unicorn."
    end
  end

  def stop
    unless unicorn_pid == ''
      system "kill -QUIT #{unicorn_pid}"
      puts "Stopped unicorn."
    end
  end

  def status
    print "unicorn status: "
    if unicorn_pid == ''
      puts "STOPPED"
    else
      puts "RUNNING"
      puts "master PID: #{unicorn_pid}"
    end
  end

  def unicorn_pid
    return @pid unless @pid.nil?
    @pid = ''
    pidfiles = Dir.glob('tmp/pids/unicorn_*.pid')
    pidfiles.each do |pidfile|
      p = File.read(pidfile).strip
      `kill -s 0 #{p} 2> /dev/null`
      if $?.success?
        @pid << "#{p} "
      else
        File.delete(pidfile)
      end
    end
    @pid
  end

  def print_usage
    puts 'USAGE: script/unicorn command [environment]'
    puts ''
    puts '    command:     start, restart, stop, status'
    puts "    environment: the environment used to start unicorn, defaults to 'development'"
    puts ''
  end

end

UnicornTasks.new(ARGV).exec
